### ISSUE TITLE
Weekly to-do list (28th, Feb, 2022)

### ISSUE THREAD

**Issue by xingjianleng** [xingjianleng/DBGA#1]
Below is the list of to-dos from 28th, Feb, 2022 to 6th, Mar, 2022.
- [x] Fork and clone [cogent3](https://github.com/cogent3/cogent3) and [c3dev](https://github.com/cogent3/c3dev) repositories to local machine.
- [x] Install [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install) (WSL2) and set up Python virtualenv for development.
- [x] Investigate the [pathlib](https://docs.python.org/3/library/pathlib.html) library and check how it can be used.
- [x] Try some code with cogent3 (especially about sequence alignment), and think of possible ways to measure the performance of sequence alignment algorithms.
- [x] Search for (third-party) utilities for profiling the memory usage during algorithm execution. (Runtime of the algorithm is not the key point as Python itself is slow.)
- [x] Re-read the partial order graph and de Bruijn graph (or possibly A-Bruijn graph) and figure out the similarities and differences betwen them. What are their pros and cons? Make some notes.
- [x] Try different dynamic programming algorithms for sequence alignment (e.g. Needleman-Wunsch) and see where they fit.
